config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "lists#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :list, uniqueness: { scope: :movie }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<nav class="navbar navbar-light bg-light px-5">
  <i class="fa-solid fa-film"></i>
  <form class="form-inline pull-right">
    <%= link_to "Home", lists_path, class: "btn btn-outline-success my-2 my-sm-0" %>
  </form>
</nav>
<div class="text-center">
  <h1>Create a new bookmark:</h1>
</div>
<div class="container w-50">
    <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.association :movie, prompt: "Choose a movie" %>
          <%= f.input :comment, placeholder: 'Enter a comment' %>
          <%= f.submit class: "btn btn-flat" %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<nav class="navbar navbar-light bg-light px-5">
  <%= link_to lists_path do %>
    <i class="fa-solid fa-film" style="color: green;"></i>
    <% end %>
  <form class="form-inline">
    <%= link_to "Add list", new_list_path, class: "btn btn-outline-success my-2 my-sm-0", style: "green" %>
  </form>
</nav>

<div class="row m-2">
  <% @lists.each do |list| %>
  <div class="card m-2" style="width: 18rem;">
    <img class="card-img-top " src=<%= cl_image_path list.photo.key, height: 300, crop: :fill %> alt="Card image cap">
    <div class="card-body text-center">
      <%= link_to list.name, list_path(list), class: "btn btn-primary"  %>
    </div>
  </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="text-center">
  <h1>Create a new list:</h1>
</div>
<div class="container w-50">
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<nav class="navbar navbar-light bg-light px-5">
  <i class="fa-solid fa-film"></i>
  <form class="form-inline pull-right">
    <%= link_to "Home", lists_path, class: "btn btn-outline-success my-2 my-sm-0" %>
    <%= link_to "add bookmark", new_list_bookmark_path(@list), class: "btn btn-outline-success my-2 my-sm-0" %>
  </form>
</nav>
<div class="card-category bg-cover" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path @list.photo.key, height: 300, crop: :fill, class: "img-fluid" %>)">
  <%= @list.name %>
</div>

  <div class="row m-4">
       <% @list.movies.each do |movie| %>
        <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
          <div class="col-3 m-3">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title"><%= movie.title %></h5>
                <%# < class="card-subtitle"><%= movie.overview %>
                <p class="card-text"><%= bookmark.comment %></p>
              </div>
              <div class="container">
                <div class="row">
                  <div class="col-3">
                  <%= link_to "Delete", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger mb-2" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
      <% end %>
  </div>